### ISSUE TITLE
HeuristicDiveMIP::solution asserts with honor_original_bounds=no from ipopt 3.14.x

### ISSUE THREAD

**Issue by jschueller** [coin-or/Bonmin#24]
with ipopt 3.14 I get this assertion with BB algorithm:
```
BonHeuristicDiveMIP.cpp:133: virtual int Bonmin::HeuristicDiveMIP::solution(double&, double*): Assertion `isNlpFeasible(minlp, primalTolerance)' failed.
```

I found out that ipopt 3.14 changes the default value of honor_original_bounds and that triggers the assertion wrt ipopt<3.14
For now I need to set honor_original_bounds=yes.
Should something be changed in Bonmin regarding ipopt>=3.14 ?
I'm also wondering if a new release is expected.

**Comment by svigerske** [comment]
Thanks for tracking this down.
The only thing I checked with regard to Ipopt 3.14 was that Bonmin still compiles, though with plenty of deprecation warnings. make test also passed, I believe.

I'm adding the honor_original_bounds=yes to the place where Bonmin changes Ipopt options. I hope that will do. An alternative would be to be more relaxed in `isNlpFeasible()`.

**Comment by svigerske** [comment]
Regarding releases from master, Bonmin waits for Cbc to do a release.
