### ISSUE TITLE
Can Bonmin solve a problem with semidefinite matrix variables

### ISSUE THREAD

**Issue by research20** [coin-or/Bonmin#9]
Hello,

I am using Bonmin to solve a mixed integer nonlinear problem. But the optimization variables involve a semidefinite matrix variable. Can it be solved with Bonmin, or could you give me some advice about how to make it solvable. Thanks a lot.

Best regards,
Min

**Comment by svigerske** [comment]
No, there is no support for this in Bonmin.

There are a number of SDP solvers out there (CSDP, DSDP, MOSEK, and many more), and also some MISDP solvers, e.g., SCIP-SDP, that may be useful.
